ALTER TABLE "user"
ADD COLUMN "preferredJobFunction" TEXT NOT NULL DEFAULT 'Other';

ALTER TABLE jobs
ADD COLUMN job_functions TEXT NOT NULL DEFAULT '|Other|';

UPDATE jobs
SET job_functions =
  '|' ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*finance*'
    OR lower(COALESCE(admin_title, title)) GLOB '*financial*'
    OR lower(COALESCE(admin_title, title)) GLOB '*accounting*'
    OR lower(COALESCE(admin_title, title)) GLOB '*accounts*'
    OR lower(COALESCE(admin_title, title)) GLOB '*accountant*'
    OR lower(COALESCE(admin_title, title)) GLOB '*audit*'
    OR lower(COALESCE(admin_title, title)) GLOB '*billing*'
    OR lower(COALESCE(admin_title, title)) GLOB '*budget*'
    OR lower(COALESCE(admin_title, title)) GLOB '*cash*'
    OR lower(COALESCE(admin_title, title)) GLOB '*credit*'
    OR lower(COALESCE(admin_title, title)) GLOB '*collection*'
    OR lower(COALESCE(admin_title, title)) GLOB '*treasury*'
    OR lower(COALESCE(admin_title, title)) GLOB '*tax*'
    OR lower(COALESCE(admin_title, title)) GLOB '*vat*'
    OR lower(COALESCE(admin_title, title)) GLOB '*remittance*'
    OR lower(COALESCE(admin_title, title)) GLOB '*banker*'
    OR lower(COALESCE(admin_title, title)) GLOB '*banking*'
    OR lower(COALESCE(admin_title, title)) GLOB '*investment*'
    THEN 'Finance & Accounting|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*marketing*'
    OR lower(COALESCE(admin_title, title)) GLOB '*brand*'
    OR lower(COALESCE(admin_title, title)) GLOB '*communication*'
    OR lower(COALESCE(admin_title, title)) GLOB '*media*'
    OR lower(COALESCE(admin_title, title)) GLOB '*content*'
    OR lower(COALESCE(admin_title, title)) GLOB '*public relations*'
    OR lower(COALESCE(admin_title, title)) GLOB '*martech*'
    OR lower(COALESCE(admin_title, title)) GLOB '*promotion*'
    OR lower(COALESCE(admin_title, title)) GLOB '*advertising*'
    OR lower(COALESCE(admin_title, title)) GLOB '*growth*'
    OR lower(COALESCE(admin_title, title)) GLOB '*visibility*'
    OR lower(COALESCE(admin_title, title)) GLOB '*lifecycle*'
    OR lower(COALESCE(admin_title, title)) GLOB '*campaign*'
    THEN 'Marketing & Communications|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*sales*'
    OR lower(COALESCE(admin_title, title)) GLOB '*business development*'
    OR lower(COALESCE(admin_title, title)) GLOB '*commercial*'
    OR lower(COALESCE(admin_title, title)) GLOB '*territory*'
    OR lower(COALESCE(admin_title, title)) GLOB '*key account*'
    OR lower(COALESCE(admin_title, title)) GLOB '*account management*'
    OR lower(COALESCE(admin_title, title)) GLOB '*relationship manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*relationship officer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*partnership*'
    OR lower(COALESCE(admin_title, title)) GLOB '*acquisition*'
    OR lower(COALESCE(admin_title, title)) GLOB '*export*'
    OR lower(COALESCE(admin_title, title)) GLOB '*tender*'
    THEN 'Sales & Business Development|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*software*'
    OR lower(COALESCE(admin_title, title)) GLOB '*developer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*front-end*'
    OR lower(COALESCE(admin_title, title)) GLOB '*frontend*'
    OR lower(COALESCE(admin_title, title)) GLOB '*full-stack*'
    OR lower(COALESCE(admin_title, title)) GLOB '*android*'
    OR lower(COALESCE(admin_title, title)) GLOB '*ios*'
    OR lower(COALESCE(admin_title, title)) GLOB '*flutter*'
    OR lower(COALESCE(admin_title, title)) GLOB '*react*'
    OR lower(COALESCE(admin_title, title)) GLOB '*java*'
    OR lower(COALESCE(admin_title, title)) GLOB '*.net*'
    OR lower(COALESCE(admin_title, title)) GLOB '*devops*'
    OR lower(COALESCE(admin_title, title)) GLOB '*sre*'
    OR lower(COALESCE(admin_title, title)) GLOB '*platform engineer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*qa engineer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*sqa*'
    OR lower(COALESCE(admin_title, title)) GLOB '*testing*'
    OR lower(COALESCE(admin_title, title)) GLOB '*network engineer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*security*'
    OR lower(COALESCE(admin_title, title)) GLOB '*system administrator*'
    OR lower(COALESCE(admin_title, title)) GLOB '*it operations*'
    OR lower(COALESCE(admin_title, title)) GLOB '*erp*'
    THEN 'Software & IT|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*data*'
    OR lower(COALESCE(admin_title, title)) GLOB '*analytics*'
    OR lower(COALESCE(admin_title, title)) GLOB '*business intelligence*'
    OR lower(COALESCE(admin_title, title)) GLOB '*machine learning*'
    OR lower(COALESCE(admin_title, title)) GLOB '*artificial intelligence*'
    OR lower(COALESCE(admin_title, title)) GLOB '*gen ai*'
    OR lower(COALESCE(admin_title, title)) GLOB '*measurement*'
    THEN 'Data & Analytics|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*product manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*product management*'
    OR lower(COALESCE(admin_title, title)) GLOB '*product marketing*'
    OR lower(COALESCE(admin_title, title)) GLOB '*project manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*project management*'
    OR lower(COALESCE(admin_title, title)) GLOB '*program manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*programme manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*strategy*'
    OR lower(COALESCE(admin_title, title)) GLOB '*strategic planning*'
    OR lower(COALESCE(admin_title, title)) GLOB '*pmo*'
    OR lower(COALESCE(admin_title, title)) GLOB '*uat management*'
    THEN 'Product, Project & Strategy|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*ui/ux*'
    OR lower(COALESCE(admin_title, title)) GLOB '*designer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*design*'
    OR lower(COALESCE(admin_title, title)) GLOB '*creative*'
    OR lower(COALESCE(admin_title, title)) GLOB '*animat*'
    OR lower(COALESCE(admin_title, title)) GLOB '*artist*'
    OR lower(COALESCE(admin_title, title)) GLOB '*motion*'
    THEN 'Design & Creative|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*operation*'
    OR lower(COALESCE(admin_title, title)) GLOB '*supply chain*'
    OR lower(COALESCE(admin_title, title)) GLOB '*logistics*'
    OR lower(COALESCE(admin_title, title)) GLOB '*warehouse*'
    OR lower(COALESCE(admin_title, title)) GLOB '*procurement*'
    OR lower(COALESCE(admin_title, title)) GLOB '*production*'
    OR lower(COALESCE(admin_title, title)) GLOB '*manufacturing*'
    OR lower(COALESCE(admin_title, title)) GLOB '*merchandising*'
    OR lower(COALESCE(admin_title, title)) GLOB '*courier*'
    OR lower(COALESCE(admin_title, title)) GLOB '*distribution*'
    OR lower(COALESCE(admin_title, title)) GLOB '*fleet*'
    OR lower(COALESCE(admin_title, title)) GLOB '*mechanic*'
    OR lower(COALESCE(admin_title, title)) GLOB '*driver*'
    OR lower(COALESCE(admin_title, title)) GLOB '*runner*'
    THEN 'Operations & Supply Chain|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*human resource*'
    OR lower(COALESCE(admin_title, title)) GLOB '*hrbp*'
    OR lower(COALESCE(admin_title, title)) GLOB '*hr manager*'
    OR lower(COALESCE(admin_title, title)) GLOB '*hr executive*'
    OR lower(COALESCE(admin_title, title)) GLOB '*people generalist*'
    OR lower(COALESCE(admin_title, title)) GLOB '*people partner*'
    OR lower(COALESCE(admin_title, title)) GLOB '*people experience*'
    OR lower(COALESCE(admin_title, title)) GLOB '*talent acquisition*'
    OR lower(COALESCE(admin_title, title)) GLOB '*employee relations*'
    OR lower(COALESCE(admin_title, title)) GLOB '*learning & development*'
    THEN 'People & Human Resources|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*customer service*'
    OR lower(COALESCE(admin_title, title)) GLOB '*customer success*'
    OR lower(COALESCE(admin_title, title)) GLOB '*customer experience*'
    OR lower(COALESCE(admin_title, title)) GLOB '*client service*'
    OR lower(COALESCE(admin_title, title)) GLOB '*client success*'
    OR lower(COALESCE(admin_title, title)) GLOB '*product support*'
    OR lower(COALESCE(admin_title, title)) GLOB '*support coordinator*'
    OR lower(COALESCE(admin_title, title)) GLOB '*support specialist*'
    OR lower(COALESCE(admin_title, title)) GLOB '*partner service*'
    OR lower(COALESCE(admin_title, title)) GLOB '*call quality*'
    OR lower(COALESCE(admin_title, title)) GLOB '*front desk*'
    THEN 'Customer Service & Support|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*legal*'
    OR lower(COALESCE(admin_title, title)) GLOB '*compliance*'
    OR lower(COALESCE(admin_title, title)) GLOB '*aml*'
    OR lower(COALESCE(admin_title, title)) GLOB '*cft*'
    OR lower(COALESCE(admin_title, title)) GLOB '*fraud*'
    OR lower(COALESCE(admin_title, title)) GLOB '*risk*'
    OR lower(COALESCE(admin_title, title)) GLOB '*governance*'
    OR lower(COALESCE(admin_title, title)) GLOB '*regulatory*'
    OR lower(COALESCE(admin_title, title)) GLOB '*documentation*'
    THEN 'Legal, Risk & Compliance|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*instructor*'
    OR lower(COALESCE(admin_title, title)) GLOB '*teacher*'
    OR lower(COALESCE(admin_title, title)) GLOB '*academic*'
    OR lower(COALESCE(admin_title, title)) GLOB '*education*'
    OR lower(COALESCE(admin_title, title)) GLOB '*research*'
    OR lower(COALESCE(admin_title, title)) GLOB '*training*'
    OR lower(COALESCE(admin_title, title)) GLOB '*learning facilitation*'
    OR lower(COALESCE(admin_title, title)) GLOB '*counsellor*'
    OR lower(COALESCE(admin_title, title)) GLOB '*curriculum*'
    THEN 'Education & Research|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*healthcare*'
    OR lower(COALESCE(admin_title, title)) GLOB '*healthtech*'
    OR lower(COALESCE(admin_title, title)) GLOB '*pharma*'
    OR lower(COALESCE(admin_title, title)) GLOB '*medical*'
    OR lower(COALESCE(admin_title, title)) GLOB '*medico*'
    OR lower(COALESCE(admin_title, title)) GLOB '*clinical*'
    OR lower(COALESCE(admin_title, title)) GLOB '*doctor*'
    OR lower(COALESCE(admin_title, title)) GLOB '*hospital*'
    OR lower(COALESCE(admin_title, title)) GLOB '*life science*'
    OR lower(COALESCE(admin_title, title)) GLOB '*r&d*'
    THEN 'Healthcare & Life Sciences|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*engineer*'
    OR lower(COALESCE(admin_title, title)) GLOB '*engineering*'
    OR lower(COALESCE(admin_title, title)) GLOB '*technical*'
    OR lower(COALESCE(admin_title, title)) GLOB '*machinery*'
    OR lower(COALESCE(admin_title, title)) GLOB '*machineries*'
    OR lower(COALESCE(admin_title, title)) GLOB '*maintenance*'
    OR lower(COALESCE(admin_title, title)) GLOB '*electrical*'
    OR lower(COALESCE(admin_title, title)) GLOB '*mechanical*'
    THEN 'Engineering & Technical|' ELSE '' END ||
  CASE WHEN lower(COALESCE(admin_title, title)) GLOB '*administration*'
    OR lower(COALESCE(admin_title, title)) GLOB '*administrative*'
    OR lower(COALESCE(admin_title, title)) GLOB '*admin*'
    OR lower(COALESCE(admin_title, title)) GLOB '*office management*'
    OR lower(COALESCE(admin_title, title)) GLOB '*secretary*'
    THEN 'Administration|' ELSE '' END;

UPDATE jobs
SET job_functions = '|Other|'
WHERE job_functions = '|';
